#!/bin/bash

PROGRAM="./a.out"  # Remplace par ton exécutable si nécessaire
TEST_DIR="bsq_test_maps"

mkdir -p $TEST_DIR
rm -f $TEST_DIR/*.txt

# --------------------------
# Map 1: Classique valide
cat > $TEST_DIR/map1.txt << EOF
9 . o x
...........................
....o......................
............o..............
...........................
....o......................
...............o...........
...........................
......o..............o.....
..o.......o................
EOF

# --------------------------
# Map 2: Petite valide
cat > $TEST_DIR/map2.txt << EOF
5 . o x
.....
.o...
.....
..o..
.....
EOF

# --------------------------
# Map invalide 1: caractère inconnu
cat > $TEST_DIR/map_invalid1.txt << EOF
5 . o x
.....
..a..
.....
.o...
.....
EOF

# --------------------------
# Map invalide 2: ligne trop courte
cat > $TEST_DIR/map_invalid2.txt << EOF
5 . o x
.....
..o..
....
.o...
.....
EOF

# --------------------------
# Map edge case: carré 1
cat > $TEST_DIR/map_edge.txt << EOF
3 . o x
ooo
o.o
ooo
EOF

# --------------------------
# Map grande: 20x20
cat > $TEST_DIR/map_big.txt << EOF
20 . o x
....................
.....o..............
...........o........
....................
..o.................
........o...........
....................
.....o..............
....................
..............o.....
....................
...o................
....................
........o...........
....................
....................
.o..................
....................
...........o........
....................
EOF

# --------------------------
# Map full obstacles
cat > $TEST_DIR/map_full_obstacles.txt << EOF
5 . o x
ooooo
ooooo
ooooo
ooooo
ooooo
EOF

# --------------------------
# Map all empty
cat > $TEST_DIR/map_all_empty.txt << EOF
5 . o x
.....
.....
.....
.....
.....
EOF

# --------------------------
# Lancer les tests
for f in $TEST_DIR/*.txt; do
    echo "==== Testing $f ===="
    $PROGRAM "$f"
    echo ""
done