
services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - docker_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    secrets:
      - db_password
      - db_user
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
    networks:
      - docker_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    secrets:
    - db_password
    - db_root_password
    - db_user
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - docker_network
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  redis:
    build:
      context: ./requirements/bonus/redis
    image: redis
    networks:
      - docker_network
    restart: always

  vsftpd:
    build:
      context: ./requirements/bonus/vsftpd
    image: vsftpd
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    secrets:
    - ftp_password
    - ftp_user
    networks:
      - docker_network
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  static-site:
    build:
      context: ./requirements/bonus/static-site
    image: static-site
    ports:
      - "80:80"
    networks:
      - docker_network
    restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb

networks:
  docker_network:

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user:
    file: ../secrets/credentials.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  ftp_user:
    file: ../secrets/ftp_user.txt